// <auto-generated />
using Mercadona.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mercadona.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230627070720_SendCategoryTableToDb")]
    partial class SendCategoryTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mercadona.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fresh Produce",
                            Url = "fresh_produce"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Meat and Poultry",
                            Url = "meat_poultry"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Seafood",
                            Url = "seafood"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dairy and Eggs",
                            Url = "dairy_eggs"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Snacks and Confectionery",
                            Url = "snacks_confectionery"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bakery",
                            Url = "bakery"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Beverages",
                            Url = "beverages"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Household Essential",
                            Url = "household_essential"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Personal Care",
                            Url = "personal_care"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Pharmacy",
                            Url = "pharmacy"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Home Appliance",
                            Url = "home_appliance"
                        },
                        new
                        {
                            Id = 12,
                            Name = "DIY",
                            Url = "diy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
