// <auto-generated />
using System;
using Mercadona.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mercadona.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230703093114_DiscountTest")]
    partial class DiscountTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mercadona.Models.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("character varying(30)");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Categories");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Name = "Fresh Produce",
                        Url = "fresh_produce"
                    },
                    new
                    {
                        Id = 2,
                        Name = "Meat and Poultry",
                        Url = "meat_poultry"
                    },
                    new
                    {
                        Id = 3,
                        Name = "Seafood",
                        Url = "seafood"
                    },
                    new
                    {
                        Id = 4,
                        Name = "Dairy and Eggs",
                        Url = "dairy_eggs"
                    },
                    new
                    {
                        Id = 5,
                        Name = "Snacks and Confectionery",
                        Url = "snacks_confectionery"
                    },
                    new
                    {
                        Id = 6,
                        Name = "Bakery",
                        Url = "bakery"
                    },
                    new
                    {
                        Id = 7,
                        Name = "Beverages",
                        Url = "beverages"
                    },
                    new
                    {
                        Id = 8,
                        Name = "Household Essential",
                        Url = "household_essential"
                    },
                    new
                    {
                        Id = 9,
                        Name = "Personal Care",
                        Url = "personal_care"
                    },
                    new
                    {
                        Id = 10,
                        Name = "Pharmacy",
                        Url = "pharmacy"
                    },
                    new
                    {
                        Id = 11,
                        Name = "Home Appliance",
                        Url = "home_appliance"
                    },
                    new
                    {
                        Id = 12,
                        Name = "DIY",
                        Url = "diy"
                    });
            });

            modelBuilder.Entity("Mercadona.Models.Discount", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("DiscountValue")
                    .HasColumnType("integer");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("timestamp without time zone");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("character varying(30)");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("timestamp without time zone");

                b.HasKey("Id");

                b.ToTable("Discounts");

                b.HasData(
                    new
                    {
                        Id = 1,
                        DiscountValue = 25,
                        EndDate = new DateTime(2023, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Christmas Discount",
                        StartDate = new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    },
                    new
                    {
                        Id = 2,
                        DiscountValue = 15,
                        EndDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Winter Discount",
                        StartDate = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    },
                    new
                    {
                        Id = 3,
                        DiscountValue = 10,
                        EndDate = new DateTime(2023, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "DIY Discount",
                        StartDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    },
                    new
                    {
                        Id = 4,
                        DiscountValue = 10,
                        EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Summer Discount",
                        StartDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    });
            });

            modelBuilder.Entity("Mercadona.Models.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("CategoryId")
                    .HasColumnType("integer");

                b.Property<string>("Desc")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int?>("DiscountId")
                    .HasColumnType("integer");

                b.Property<decimal?>("DiscountedPrice")
                    .HasColumnType("numeric");

                b.Property<string>("ImageUrl")
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal>("Price")
                    .HasColumnType("numeric");

                b.HasKey("Id");

                b.HasIndex("CategoryId");

                b.HasIndex("DiscountId");

                b.ToTable("Products");

                b.HasData(
                    new
                    {
                        Id = 1,
                        CategoryId = 1,
                        Desc = "A pack of 6 juicy and fresh organic red apples.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/red-apples.jpg",
                        Name = "Organic Red Apples",
                        Price = 4.99m
                    },
                    new
                    {
                        Id = 2,
                        CategoryId = 1,
                        Desc = "Crisp and fresh romaine lettuce, perfect for salads.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/romaine-lettuce.jpg",
                        Name = "Romaine Lettuce",
                        Price = 1.49m
                    },
                    new
                    {
                        Id = 3,
                        CategoryId = 1,
                        Desc = "A 1-pound bag of sweet and crunchy organic carrots.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/carrots.jpg",
                        Name = "Organic Carrots",
                        Price = 1.99m
                    },
                    new
                    {
                        Id = 4,
                        CategoryId = 1,
                        Desc = "A pack of 4 fresh and sweet corn on the cob.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/sweet-corn.jpg",
                        Name = "Sweet Corn",
                        Price = 2.49m
                    },
                    new
                    {
                        Id = 5,
                        CategoryId = 1,
                        Desc = "A 1-pound bag of fresh and nutritious organic broccoli.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/broccoli.jpg",
                        Name = "Organic Broccoli",
                        Price = 2.99m
                    },
                    new
                    {
                        Id = 6,
                        CategoryId = 1,
                        Desc = "A 1-pound bag of sweet and juicy seedless red grapes.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/red-grapes.jpg",
                        Name = "Seedless Red Grapes",
                        Price = 3.49m
                    },
                    new
                    {
                        Id = 7,
                        CategoryId = 2,
                        Desc = "A 1.5-pound package of fresh, boneless, and skinless chicken breasts.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/chicken-breasts.jpg",
                        Name = "Boneless Skinless Chicken Breasts",
                        Price = 6.99m
                    },
                    new
                    {
                        Id = 8,
                        CategoryId = 2,
                        Desc = "A 1-pound package of 85% lean ground beef, perfect for burgers and meatloaf.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/ground-beef.jpg",
                        Name = "Ground Beef",
                        Price = 4.49m
                    },
                    new
                    {
                        Id = 9,
                        CategoryId = 2,
                        Desc = "A 1.25-pound package of bone-in center-cut pork chops.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/pork-chops.jpg",
                        Name = "Pork Chops",
                        Price = 5.99m
                    },
                    new
                    {
                        Id = 10,
                        CategoryId = 2,
                        Desc = "A 12-ounce USDA choice New York strip steak, perfect for grilling.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/new-york-strip-steak.jpg",
                        Name = "New York Strip Steak",
                        Price = 9.99m
                    },
                    new
                    {
                        Id = 11,
                        CategoryId = 2,
                        Desc = "A 4-pound whole chicken, ideal for roasting or grilling.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/whole-chicken.jpg",
                        Name = "Whole Chicken",
                        Price = 8.49m
                    },
                    new
                    {
                        Id = 12,
                        CategoryId = 2,
                        Desc = "A 1-pound package of lean and flavorful turkey sausage links.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/turkey-sausage.jpg",
                        Name = "Turkey Sausage",
                        Price = 4.29m
                    },
                    new
                    {
                        Id = 13,
                        CategoryId = 3,
                        Desc = "A pack of 2 fresh Atlantic salmon fillets, rich in Omega-3.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/salmon-fillets.jpg",
                        Name = "Atlantic Salmon Fillets",
                        Price = 11.99m
                    },
                    new
                    {
                        Id = 14,
                        CategoryId = 3,
                        Desc = "A 1-pound bag of cooked and peeled shrimp, ready to eat.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/cooked-shrimp.jpg",
                        Name = "Cooked Shrimp",
                        Price = 12.99m
                    },
                    new
                    {
                        Id = 15,
                        CategoryId = 3,
                        Desc = "A dozen fresh and succulent oysters, perfect for a seafood feast.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/oysters.jpg",
                        Name = "Fresh Oysters",
                        Price = 14.99m
                    },
                    new
                    {
                        Id = 16,
                        CategoryId = 3,
                        Desc = "A pack of 2 fresh cod fillets, great for fish and chips.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/cod-fillets.jpg",
                        Name = "Cod Fillets",
                        Price = 9.99m
                    },
                    new
                    {
                        Id = 17,
                        CategoryId = 3,
                        Desc = "A live and fresh Atlantic lobster, perfect for a special meal.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/live-lobster.jpg",
                        Name = "Live Lobster",
                        Price = 19.99m
                    },
                    new
                    {
                        Id = 18,
                        CategoryId = 3,
                        Desc = "A 1-pound block of sushi-grade tuna, perfect for sushi or sashimi.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/sushi-tuna.jpg",
                        Name = "Sushi Grade Tuna",
                        Price = 16.99m
                    },
                    new
                    {
                        Id = 19,
                        CategoryId = 4,
                        Desc = "A dozen large, cage-free brown eggs.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/brown-eggs.jpg",
                        Name = "Large Brown Eggs",
                        Price = 2.99m
                    },
                    new
                    {
                        Id = 20,
                        CategoryId = 4,
                        Desc = "A 1-gallon jug of fresh and creamy whole milk.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/whole-milk.jpg",
                        Name = "Whole Milk",
                        Price = 3.49m
                    },
                    new
                    {
                        Id = 21,
                        CategoryId = 4,
                        Desc = "A 1-pound package of unsalted butter.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/unsalted-butter.jpg",
                        Name = "Unsalted Butter",
                        Price = 4.49m
                    },
                    new
                    {
                        Id = 22,
                        CategoryId = 4,
                        Desc = "A 1-pound block of sharp cheddar cheese.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/cheddar-cheese.jpg",
                        Name = "Sharp Cheddar Cheese",
                        Price = 5.99m
                    },
                    new
                    {
                        Id = 23,
                        CategoryId = 4,
                        Desc = "A 32-ounce container of plain, non-fat Greek yogurt.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/greek-yogurt.jpg",
                        Name = "Greek Yogurt",
                        Price = 4.99m
                    },
                    new
                    {
                        Id = 24,
                        CategoryId = 4,
                        Desc = "A 1-pint carton of heavy whipping cream.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/heavy-cream.jpg",
                        Name = "Heavy Cream",
                        Price = 2.99m
                    },
                    new
                    {
                        Id = 25,
                        CategoryId = 5,
                        Desc = "A 10-ounce bag of crispy and delicious classic potato chips.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/potato-chips.jpg",
                        Name = "Classic Potato Chips",
                        Price = 3.49m
                    },
                    new
                    {
                        Id = 26,
                        CategoryId = 5,
                        Desc = "A 3.5-ounce bar of rich and smooth dark chocolate.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/dark-chocolate.jpg",
                        Name = "Dark Chocolate Bar",
                        Price = 2.99m
                    },
                    new
                    {
                        Id = 27,
                        CategoryId = 5,
                        Desc = "A 1-pound bag of soft and chewy assorted gummy bears.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/gummy-bears.jpg",
                        Name = "Gummy Bears",
                        Price = 3.99m
                    },
                    new
                    {
                        Id = 28,
                        CategoryId = 5,
                        Desc = "A 16-ounce jar of crunchy and salted peanuts.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/salted-peanuts.jpg",
                        Name = "Salted Peanuts",
                        Price = 4.29m
                    },
                    new
                    {
                        Id = 29,
                        CategoryId = 5,
                        Desc = "A 7-ounce bag of air-popped popcorn coated in white cheddar.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/white-cheddar-popcorn.jpg",
                        Name = "White Cheddar Popcorn",
                        Price = 3.79m
                    },
                    new
                    {
                        Id = 30,
                        CategoryId = 5,
                        Desc = "A 12-ounce bag of crunchy and salty pretzel sticks.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/pretzel-sticks.jpg",
                        Name = "Pretzel Sticks",
                        Price = 2.99m
                    },
                    new
                    {
                        Id = 31,
                        CategoryId = 6,
                        Desc = "A 1-pound loaf of freshly baked sourdough bread.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/sourdough-bread.jpg",
                        Name = "Sourdough Bread",
                        Price = 3.99m
                    },
                    new
                    {
                        Id = 32,
                        CategoryId = 6,
                        Desc = "A pack of 12 soft and chewy chocolate chip cookies.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/chocolate-chip-cookies.jpg",
                        Name = "Chocolate Chip Cookies",
                        Price = 4.49m
                    },
                    new
                    {
                        Id = 33,
                        CategoryId = 6,
                        Desc = "A pack of 4 delicious and moist blueberry muffins.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/blueberry-muffins.jpg",
                        Name = "Blueberry Muffins",
                        Price = 3.99m
                    },
                    new
                    {
                        Id = 34,
                        CategoryId = 6,
                        Desc = "A freshly baked and crusty French baguette.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/french-baguette.jpg",
                        Name = "French Baguette",
                        Price = 2.49m
                    },
                    new
                    {
                        Id = 35,
                        CategoryId = 6,
                        Desc = "A pack of 6 freshly baked cinnamon rolls with icing.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/cinnamon-rolls.jpg",
                        Name = "Cinnamon Rolls",
                        Price = 5.99m
                    },
                    new
                    {
                        Id = 36,
                        CategoryId = 6,
                        Desc = "A 1-pound loaf of freshly baked whole wheat bread.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/whole-wheat-bread.jpg",
                        Name = "Whole Wheat Bread",
                        Price = 3.49m
                    },
                    new
                    {
                        Id = 37,
                        CategoryId = 7,
                        Desc = "A 64-ounce bottle of 100% freshly squeezed orange juice.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/orange-juice.jpg",
                        Name = "Orange Juice",
                        Price = 4.49m
                    },
                    new
                    {
                        Id = 38,
                        CategoryId = 7,
                        Desc = "A pack of 24 16.9-ounce bottles of purified water.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/bottled-water.jpg",
                        Name = "Bottled Water",
                        Price = 3.99m
                    },
                    new
                    {
                        Id = 39,
                        CategoryId = 7,
                        Desc = "A box of 20 green tea bags, perfect for a healthy and refreshing drink.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/green-tea.jpg",
                        Name = "Green Tea",
                        Price = 3.49m
                    },
                    new
                    {
                        Id = 40,
                        CategoryId = 7,
                        Desc = "A pack of 12 12-ounce cans of refreshing cola soda.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/cola-soda.jpg",
                        Name = "Cola Soda",
                        Price = 4.99m
                    },
                    new
                    {
                        Id = 41,
                        CategoryId = 7,
                        Desc = "A pack of 8 20-ounce bottles of electrolyte-enhanced sports drink.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/sports-drink.jpg",
                        Name = "Sports Drink",
                        Price = 6.49m
                    },
                    new
                    {
                        Id = 42,
                        CategoryId = 7,
                        Desc = "A 64-ounce carton of unsweetened almond milk.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/almond-milk.jpg",
                        Name = "Almond Milk",
                        Price = 3.79m
                    },
                    new
                    {
                        Id = 43,
                        CategoryId = 8,
                        Desc = "A pack of 12 double rolls of soft and strong 2-ply toilet paper.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/toilet-paper.jpg",
                        Name = "Toilet Paper",
                        Price = 6.99m
                    },
                    new
                    {
                        Id = 44,
                        CategoryId = 8,
                        Desc = "A pack of 6 big rolls of absorbent and durable paper towels.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/paper-towels.jpg",
                        Name = "Paper Towels",
                        Price = 5.49m
                    },
                    new
                    {
                        Id = 45,
                        CategoryId = 8,
                        Desc = "A 32-ounce bottle of all-purpose cleaner, suitable for various surfaces.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/all-purpose-cleaner.jpg",
                        Name = "All-Purpose Cleaner",
                        Price = 2.99m
                    },
                    new
                    {
                        Id = 46,
                        CategoryId = 8,
                        Desc = "A 100-ounce bottle of liquid laundry detergent, enough for 64 loads.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/laundry-detergent.jpg",
                        Name = "Laundry Detergent",
                        Price = 9.99m
                    },
                    new
                    {
                        Id = 47,
                        CategoryId = 8,
                        Desc = "A 24-ounce bottle of dishwashing liquid, tough on grease and gentle on hands.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/dishwashing-liquid.jpg",
                        Name = "Dishwashing Liquid",
                        Price = 2.79m
                    },
                    new
                    {
                        Id = 48,
                        CategoryId = 8,
                        Desc = "A pack of 40 13-gallon tall kitchen drawstring garbage bags.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/garbage-bags.jpg",
                        Name = "Garbage Bags",
                        Price = 7.49m
                    },
                    new
                    {
                        Id = 49,
                        CategoryId = 9,
                        Desc = "A 4.7-ounce tube of fluoride toothpaste for cavity protection.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/toothpaste.jpg",
                        Name = "Toothpaste",
                        Price = 3.49m
                    },
                    new
                    {
                        Id = 50,
                        CategoryId = 9,
                        Desc = "A 12-ounce bottle of moisturizing shampoo for all hair types.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/shampoo.jpg",
                        Name = "Shampoo",
                        Price = 4.99m
                    },
                    new
                    {
                        Id = 51,
                        CategoryId = 9,
                        Desc = "An 18-ounce bottle of nourishing body wash for soft and smooth skin.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/body-wash.jpg",
                        Name = "Body Wash",
                        Price = 5.49m
                    },
                    new
                    {
                        Id = 52,
                        CategoryId = 9,
                        Desc = "A 2.7-ounce stick of antiperspirant deodorant for 24-hour protection.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/deodorant.jpg",
                        Name = "Deodorant",
                        Price = 3.99m
                    },
                    new
                    {
                        Id = 53,
                        CategoryId = 9,
                        Desc = "A box of 120 2-ply facial tissues, soft and gentle on the skin.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/facial-tissues.jpg",
                        Name = "Facial Tissues",
                        Price = 2.29m
                    },
                    new
                    {
                        Id = 54,
                        CategoryId = 9,
                        Desc = "An 8-ounce bottle of hand sanitizer, kills 99.9% of germs.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/hand-sanitizer.jpg",
                        Name = "Hand Sanitizer",
                        Price = 3.79m
                    },
                    new
                    {
                        Id = 55,
                        CategoryId = 10,
                        Desc = "A bottle of 100 200mg ibuprofen tablets for pain relief.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/ibuprofen.jpg",
                        Name = "Ibuprofen",
                        Price = 7.99m
                    },
                    new
                    {
                        Id = 56,
                        CategoryId = 10,
                        Desc = "A bottle of 60 daily multivitamin tablets for overall health.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/multivitamins.jpg",
                        Name = "Multivitamins",
                        Price = 9.49m
                    },
                    new
                    {
                        Id = 57,
                        CategoryId = 10,
                        Desc = "A box of 30 non-drowsy allergy relief tablets.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/allergy-relief.jpg",
                        Name = "Allergy Relief",
                        Price = 6.99m
                    },
                    new
                    {
                        Id = 58,
                        CategoryId = 10,
                        Desc = "A 4-ounce bottle of cough suppressant syrup for cold and flu relief.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/cough-suppressant.jpg",
                        Name = "Cough Suppressant",
                        Price = 5.49m
                    },
                    new
                    {
                        Id = 59,
                        CategoryId = 10,
                        Desc = "A box of 100 assorted sizes adhesive bandages for wound protection.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/band-aids.jpg",
                        Name = "Band-Aids",
                        Price = 4.29m
                    },
                    new
                    {
                        Id = 60,
                        CategoryId = 10,
                        Desc = "A bottle of 100 500mg extra strength acetaminophen caplets for pain and fever relief.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/acetaminophen.jpg",
                        Name = "Acetaminophen",
                        Price = 7.49m
                    },
                    new
                    {
                        Id = 61,
                        CategoryId = 11,
                        Desc = "A powerful 700-watt countertop blender with a 40-ounce glass jar.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/blender.jpg",
                        Name = "Blender",
                        Price = 49.99m
                    },
                    new
                    {
                        Id = 62,
                        CategoryId = 11,
                        Desc = "A 1000-watt countertop microwave oven with a 1.1 cubic feet capacity.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/microwave-oven.jpg",
                        Name = "Microwave Oven",
                        Price = 89.99m
                    },
                    new
                    {
                        Id = 63,
                        CategoryId = 11,
                        Desc = "A 2-slice toaster with 7 browning settings and a bagel function.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/toaster.jpg",
                        Name = "Toaster",
                        Price = 29.99m
                    },
                    new
                    {
                        Id = 64,
                        CategoryId = 11,
                        Desc = "A 6-quart programmable slow cooker with a digital timer and removable stoneware.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/slow-cooker.jpg",
                        Name = "Slow Cooker",
                        Price = 59.99m
                    },
                    new
                    {
                        Id = 65,
                        CategoryId = 11,
                        Desc = "A 1.7-liter stainless steel electric kettle with auto shut-off and boil-dry protection.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/electric-kettle.jpg",
                        Name = "Electric Kettle",
                        Price = 39.99m
                    },
                    new
                    {
                        Id = 66,
                        CategoryId = 11,
                        Desc = "A HEPA-filter air purifier with 3 fan speeds for rooms up to 300 sq. ft.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/air-purifier.jpg",
                        Name = "Air Purifier",
                        Price = 99.99m
                    },
                    new
                    {
                        Id = 67,
                        CategoryId = 12,
                        Desc = "A 20V cordless drill with a 2-speed gearbox and a 3/8-inch keyless chuck.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/cordless-drill.jpg",
                        Name = "Cordless Drill",
                        Price = 59.99m
                    },
                    new
                    {
                        Id = 68,
                        CategoryId = 12,
                        Desc = "A 9-piece paint roller set including a tray, roller frame, and various roller covers.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/paint-roller-set.jpg",
                        Name = "Paint Roller Set",
                        Price = 14.99m
                    },
                    new
                    {
                        Id = 69,
                        CategoryId = 12,
                        Desc = "A 16-ounce claw hammer with a fiberglass handle for durability and comfort.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/hammer.jpg",
                        Name = "Hammer",
                        Price = 12.99m
                    },
                    new
                    {
                        Id = 70,
                        CategoryId = 12,
                        Desc = "A 25-foot retractable tape measure with a durable, impact-resistant case.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/tape-measure.jpg",
                        Name = "Tape Measure",
                        Price = 9.99m
                    },
                    new
                    {
                        Id = 71,
                        CategoryId = 12,
                        Desc = "A 10-piece screwdriver set, including various flathead and Phillips sizes.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/screwdriver-set.jpg",
                        Name = "Screwdriver Set",
                        Price = 19.99m
                    },
                    new
                    {
                        Id = 72,
                        CategoryId = 12,
                        Desc = "A retractable utility knife with a comfortable grip and quick blade change.",
                        DiscountedPrice = 0m,
                        ImageUrl = "https://example.com/images/utility-knife.jpg",
                        Name = "Utility Knife",
                        Price = 6.99m
                    });
            });

            modelBuilder.Entity("Mercadona.Models.Product", b =>
            {
                b.HasOne("Mercadona.Models.Category", "Category")
                    .WithMany()
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Mercadona.Models.Discount", "Discount")
                    .WithMany()
                    .HasForeignKey("DiscountId");

                b.Navigation("Category");

                b.Navigation("Discount");
            });
#pragma warning restore 612, 618
        }
    }
}